name: radugidei
favicon: null
layout_spectrum: 0.20103744114749134
typography_spectrum: 0.8117980123497546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#425160'
    - '#798c9d'
    - '#ffffff'
    - '#0c0c0c'
    - '#b4c0c6'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
