name: radugidei
favicon: null
layout_spectrum: 0.90569
typography_spectrum: 0.79602
title: Radu Gidei | creative thinker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#f3c331'
    - '#5a5a5a'
    - '#919191'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
